### ISSUE TITLE
Values not usable in Particle-Mechanic

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#185]
We are trying to use a value in the particle-mechanic, but it is throwing an error in console.

![image](https://user-images.githubusercontent.com/6072971/31351967-57a8ffb4-ad2d-11e7-8dc9-c58fff0d5138.png)
![image](https://user-images.githubusercontent.com/6072971/31351986-64cfab02-ad2d-11e7-9a04-03e9188f8a4a.png)
![image](https://user-images.githubusercontent.com/6072971/31352011-743cf554-ad2d-11e7-8bd1-aa5105b72ce8.png)

`[19:54:56 WARN]: [SkillAPI] Task #30738 for SkillAPI v3.103 generated an excepti
on
java.lang.NumberFormatException: Invalid Number: varHammerAttacke
        at com.sucy.skill.api.util.NumberParser.error(NumberParser.java:147) ~[?
:?]
        at com.sucy.skill.api.util.NumberParser.parseDouble(NumberParser.java:12
3) ~[?:?]
        at com.sucy.skill.api.Settings.getScale(Settings.java:348) ~[?:?]
        at com.sucy.skill.api.Settings.getAttr(Settings.java:309) ~[?:?]
        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:153) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.ParticleMechanic.execute(ParticleMechanic.java:77) ~[?:?]
        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:201) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.RepeatMechanic.access$500(RepeatMechanic.java:41) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.RepeatMechanic$RepeatTask.run(RepeatMechanic.java:150) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

**Comment by Eniripsa96** [comment]
Values aren't currently supported with particle mechanics. I'll have to add that in.
