### ISSUE TITLE
SkillApi updateCooldown Problem [low prio]

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#186]
After playing around with a skill we got this every second:
`java.lang.NullPointerException: null
        at com.sucy.skill.api.player.PlayerSkillBar.updateCooldowns(PlayerSkillBar.java:467) ~[?:?]
        at com.sucy.skill.task.CooldownTask.run(CooldownTask.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.1-b1204.jar:git-Paper-1204]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
`

I tracked it down to the skill icon not being set (which may be our fault, but it shouldn't spam the console like this. better just throw an error at loading and disabling this one skill or so)

**Comment by MWFIAE** [comment]
Well you could check it by creating a "virtual" Inventory, adding to it and then checking if its still there...
But neither do I know if this would work in this case, nor would I recommend doing something like this, as it doesn't sound very "clean". 

One possibility would be to just silently set the skill-item to some sort of default item if its null in the update method. I think the users would be able to figure that something is not right with the material that is set in the skill.
