### ISSUE TITLE
Particals Don't work

### ISSUE THREAD

**Issue by YukiNerdCubed** [Eniripsa96/SkillAPI#225]
When I try to bind particals to skills, a error always comes up and no particals can be displayed..

[22:20:39 WARN]: [SkillAPI] Task #40 for SkillAPI v3.103 generated an exception
java.lang.NoSuchFieldError: SHEEP_EAT
        at com.sucy.skill.api.util.ParticleHelper$2.<init>(ParticleHelper.java:377) ~[?:?]
        at com.sucy.skill.api.util.ParticleHelper.<clinit>(ParticleHelper.java:373) ~[?:?]
        at com.sucy.skill.api.projectile.ParticleProjectile.run(ParticleProjectile.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-d21162c-25959fa]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Eniripsa96** [comment]
Looks like CraftBukkit 1.12 doesn't support that entity effect. Will look into a fix.
