### ISSUE TITLE
Cannot use Skillapi...

### ISSUE THREAD

**Issue by qianran0416** [Eniripsa96/SkillAPI#232]
Tried almost every version, but most of the commands didn't work. Every time I use /class profess, it says "An internal error occurred while attempting to perform this command", and my log is like this:
[00:50:00] [Server thread/INFO]: Qr___ issued server command: /class profess soldier
[00:50:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'class profess soldier' in class
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) ~[craftbukkit.jar:git-Bukkit-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:622) ~[craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1326) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1186) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-ed8c725]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit.jar:git-Bukkit-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Bukkit-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NumberFormatException: Invalid Number:  {}
	at com.sucy.skill.api.util.NumberParser.error(NumberParser.java:147) ~[?:?]
	at com.sucy.skill.api.util.NumberParser.parseDouble(NumberParser.java:123) ~[?:?]
	at com.sucy.skill.api.Settings.getScale(Settings.java:348) ~[?:?]
	at com.sucy.skill.api.Settings.getAttr(Settings.java:309) ~[?:?]
	at com.sucy.skill.api.Settings.getAttr(Settings.java:288) ~[?:?]
	at com.sucy.skill.api.classes.RPGClass.getHealth(RPGClass.java:307) ~[?:?]
	at com.sucy.skill.api.player.PlayerClass.getHealth(PlayerClass.java:191) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.updateHealthAndMana(PlayerData.java:1331) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.resetAttribs(PlayerData.java:1174) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.profess(PlayerData.java:1225) ~[?:?]
	at com.sucy.skill.cmd.CmdProfess.execute(CmdProfess.java:93) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-ed8c725]
	... 14 more

My MC is on Bukkit 1.12, and  the plugin is at the latest.

**Comment by MWFIAE** [comment]
It seems to be an issue with the health you have set (or in this case not set) for the class. 
Maybe Post your config if you can't find an error :)

**Comment by AngDrew** [comment]
Try to delete the skillapi folder
And dont forget to install mccore (skillapi dependencies)

**Comment by qianran0416** [comment]
woooow you two are awesome. You guys solved both of my issues. Big thanks and thumb up XD thannnnnnks

**Comment by MWFIAE** [comment]
Glad we could help, please close the issue :)

**Comment by Eniripsa96** [comment]
Closing the issue since it seems to be resolved. Feel free to re-open if you're still having issues.
