### ISSUE TITLE
Add Features

### ISSUE THREAD

**Issue by B4TT3RY** [Eniripsa96/SkillAPI#282]
### I think the API is not enough, so try to add a feature request.
* Add Cancelable in PlayerClassChangeEvent
* Please let me know which skill has caused the damage in SkillDamageEvent, PhysicalDamageEvent
* add setSkillMana() in PlayerCastSkillEvent

I hope it will be added.
Translate by Google

**Comment by B4TT3RY** [comment]
Good!
Can you create "**PlayerPreClassChangeEvent**"
I need a way to prevent class changes.

**Comment by B4TT3RY** [comment]
@Eniripsa96 Will this be reflected in the free version?

**Comment by B4TT3RY** [comment]
I'm finding error
```
Could not pass event PlayerPreClassChangeEvent to EffectWeapon vstable-5.9.2.001346
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at com.sucy.skill.api.player.PlayerData.profess(PlayerData.java:1400) [SkillAPI.jar:?]
	at com.sucy.skill.cmd.CmdProfess.execute(CmdProfess.java:95) [SkillAPI.jar:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550) [MCCore.jar:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558) [MCCore.jar:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516) [MCCore.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.sucy.skill.api.event.PlayerPreClassChangeEvent.getPlayerData(PlayerPreClassChangeEvent.java:46) ~[?:?]
	at com.KimDiamond.EffectWeapon.SkillAPIListener.onPreClassChangeEvent(SkillAPIListener.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	... 23 more
```

![picture](https://user-images.githubusercontent.com/12368101/41654439-71ea48c4-74c4-11e8-95a1-c96493cb7d7a.png)

**Comment by Eniripsa96** [comment]
This will be reflected in the free version, yes. Also, I will fix that issue.

**Comment by Eniripsa96** [comment]
Which method are you referring to? Also, PlayerSkillCastEvent is called before cast is performed, which is the trigger. PlayerSkillCastFailedEvent may happen after the trigger if the failed reason is the skill effect failed, however.

**Comment by B4TT3RY** [comment]
When I set setManaCost to 0, I get a notification that Mana is running out.
