### ISSUE TITLE
Problem in 1.7.10

### ISSUE THREAD

**Issue by EnderGriefeur99** [Eniripsa96/SkillAPI#288]
Problem in 1.7.10 message of error 
[23:26:42] [WARN] java.lang.NullPointerException
[23:26:42] [WARN] at com.sucy.skill.listener.KillListener.setKiller(KillListener.java:191)
[23:26:42] [WARN] at com.sucy.skill.listener.KillListener.onPhysical(KillListener.java:158)
[23:26:42] [WARN] at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
[23:26:42] [WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:26:42] [WARN] at java.lang.reflect.Method.invoke(Method.java:498)
[23:26:42] [WARN] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[23:26:42] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[23:26:42] [WARN] at com.sucy.skill.listener.MainListener.onPhysicalDamage(MainListener.java:368)
[23:26:42] [WARN] at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
[23:26:42] [WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:26:42] [WARN] at java.lang.reflect.Method.invoke(Method.java:498)
[23:26:42] [WARN] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[23:26:42] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:601)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:469)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:633)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.calculateDebuffsAndCallCB(EntityLivingBase.java:1381)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1424)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(Unknown Source)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.func_70097_a(Unknown Source)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:668)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source)
[23:26:42] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611)
[23:26:42] [WARN] at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
[23:26:42] [WARN] at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
[23:26:42] [WARN] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[23:26:42] [WARN] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[23:26:42] [WARN] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:26:42] [WARN] at java.lang.Thread.run(Thread.java:748)
[23:26:42] [ERROR] Could not pass event EntityDamageByEntityEvent to SkillAPI v3.105
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:601) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:469) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:633) [CraftEventFactory.class:1.7.10-1614.58]
at net.minecraft.entity.EntityLivingBase.calculateDebuffsAndCallCB(EntityLivingBase.java:1381) [sv.class:?]
at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1424) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(Unknown Source) [yz.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70097_a(Unknown Source) [yz.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:668) [mw.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source) [yz.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchFieldError: ARMOR_STAND
at com.sucy.skill.listener.AddonListener.onAllyCheckArmorStand(AddonListener.java:121) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
... 24 more

**Comment by Zicerite** [comment]
You should include what you were doing to cause the error, and include what type of server you are using (Spigot, Paper, etc), as well as the skill that caused it.

**Comment by EnderGriefeur99** [comment]
I'm using thermos

**Comment by EnderGriefeur99** [comment]
and another message of error 
[23:15:53] [WARN] java.lang.NullPointerException
[23:15:53] [WARN] at com.sucy.skill.listener.KillListener.(KillListener.java:68)
[23:15:53] [WARN] at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:164)
[23:15:53] [WARN] at com.sucy.skill.SkillAPI.reload(SkillAPI.java:811)
[23:15:53] [WARN] at com.sucy.skill.cmd.CmdReload.execute(CmdReload.java:53)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516)
[23:15:53] [WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[23:15:53] [WARN] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[23:15:53] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[23:15:53] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[23:15:53] [WARN] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[23:15:53] [WARN] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[23:15:53] [WARN] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[23:15:53] [WARN] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[23:15:53] [WARN] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:15:53] [WARN] at java.lang.Thread.run(Thread.java:748)
[23:15:53] [WARN] java.lang.NullPointerException
[23:15:53] [WARN] at com.sucy.skill.listener.DeathListener.(DeathListener.java:53)
[23:15:53] [WARN] at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:171)
[23:15:53] [WARN] at com.sucy.skill.SkillAPI.reload(SkillAPI.java:811)
[23:15:53] [WARN] at com.sucy.skill.cmd.CmdReload.execute(CmdReload.java:53)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558)
[23:15:53] [WARN] at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516)
[23:15:53] [WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[23:15:53] [WARN] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[23:15:53] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[23:15:53] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[23:15:53] [WARN] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[23:15:53] [WARN] at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[23:15:53] [WARN] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[23:15:53] [WARN] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[23:15:53] [WARN] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:15:53] [WARN] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:15:53] [WARN] at java.lang.Thread.run(Thread.java:748)

**Comment by Eniripsa96** [comment]
Ah, this was more of a debugging log for Thermos and it shouldn't actually affect anything. This log message is disabled in premium but it seems I forgot to do so in free. Will update that

**Comment by EnderGriefeur99** [comment]
[16:31:05] [WARN] [SkillAPI] Task #18 for SkillAPI v3.105 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (1500.522)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:821) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at com.sucy.skill.task.GUITask.run(GUITask.java:142) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by Eniripsa96** [comment]
Fixed in 3.106

**Comment by EnderGriefeur99** [comment]
Problem in 1.7.10 message of error
[23:26:42] [WARN] java.lang.NullPointerException
[23:26:42] [WARN] at com.sucy.skill.listener.KillListener.setKiller(KillListener.java:191)
[23:26:42] [WARN] at com.sucy.skill.listener.KillListener.onPhysical(KillListener.java:158)
[23:26:42] [WARN] at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
[23:26:42] [WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:26:42] [WARN] at java.lang.reflect.Method.invoke(Method.java:498)
[23:26:42] [WARN] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[23:26:42] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[23:26:42] [WARN] at com.sucy.skill.listener.MainListener.onPhysicalDamage(MainListener.java:368)
[23:26:42] [WARN] at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
[23:26:42] [WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:26:42] [WARN] at java.lang.reflect.Method.invoke(Method.java:498)
[23:26:42] [WARN] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[23:26:42] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[23:26:42] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:601)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:469)
[23:26:42] [WARN] at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:633)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.calculateDebuffsAndCallCB(EntityLivingBase.java:1381)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1424)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(Unknown Source)
[23:26:42] [WARN] at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.func_70097_a(Unknown Source)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:668)
[23:26:42] [WARN] at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source)
[23:26:42] [WARN] at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611)
[23:26:42] [WARN] at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
[23:26:42] [WARN] at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
[23:26:42] [WARN] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[23:26:42] [WARN] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[23:26:42] [WARN] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:26:42] [WARN] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:26:42] [WARN] at java.lang.Thread.run(Thread.java:748)
[23:26:42] [ERROR] Could not pass event EntityDamageByEntityEvent to SkillAPI v3.105
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:601) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:469) [CraftEventFactory.class:1.7.10-1614.58]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:633) [CraftEventFactory.class:1.7.10-1614.58]
at net.minecraft.entity.EntityLivingBase.calculateDebuffsAndCallCB(EntityLivingBase.java:1381) [sv.class:?]
at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1424) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(Unknown Source) [yz.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70097_a(Unknown Source) [yz.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:668) [mw.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source) [yz.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchFieldError: ARMOR_STAND
at com.sucy.skill.listener.AddonListener.onAllyCheckArmorStand(AddonListener.java:121) ~[?:?]
at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
... 24 more

**Comment by EnderGriefeur99** [comment]
this is not patch
