### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous player tracker update!

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#289]
`[22:14:10 ERROR]: Could not pass event InventoryCloseEvent to LixBaazar v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:895) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:937) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:404) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.pazar.Baazar.bazaarCreatePrices(Baazar.java:1163) [LixBazaar.jar:?]
        at com.pazar.Baazar.onChat(Baazar.java:1153) [LixBazaar.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:327) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:216) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.EntityPlayer.G(EntityPlayer.java:1282) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.EntityPlayer.updateAbilities(EntityPlayer.java:1139) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setWalkSpeed(CraftPlayer.java:1285) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.sucy.skill.listener.AttributeListener.updatePlayer(AttributeListener.java:333) ~[?:?]
        at com.sucy.skill.api.player.PlayerData.addBonusAttributes(PlayerData.java:448) ~[?:?]
        at com.lixrpginv.attrManager.delBonusAttr(attrManager.java:41) ~[?:?]
        at com.pazar.Baazar.onInventoryCloseEvent(Baazar.java:777) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        ... 24 more`

And
com.lixrpginv.attrManager line 41 = SkillAPI.getPlayerData(player).addBonusAttributes("offhand", -9999);

I believe this didnt happen with older versions of skillapi, I will test it

**Comment by Lix3nn53** [comment]
I am sorry for this, it might be because of me. I am doing more tests now..
Can you let me know if you have any idea why this happens?

**Comment by Lix3nn53** [comment]
Sorry this is my mistake

**Comment by LinusHojaGER** [comment]
> Sorry this is my mistake

What was the Problem and how did you fix it?
