### ISSUE TITLE
Removing an item affecting health throws an error

### ISSUE THREAD

**Issue by Catreina** [Eniripsa96/SkillAPI#29]
This error gets thrown when you have an item with lore that affects health values. The values get removed, and the value can drop below 1 even with a minimum health value of 1 in the configs.

[20:51:41 WARN]: [SkillAPI] Task #1261 for SkillAPI v3.84 generated an exception
java.lang.IllegalArgumentException: Max health must be greater than 0
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftLivingEntity.setMaxHealth(CraftLivingEntity.java:110) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.setMaxHealth(CraftPlayer.java:1215) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at com.sucy.skill.api.player.PlayerData.addMaxHealth(PlayerData.java:1337) ~[?:?]
        at com.sucy.skill.listener.AttributeListener.updatePlayer(AttributeListener.java:229) ~[?:?]
        at com.sucy.skill.api.player.PlayerData.addBonusAttributes(PlayerData.java:334) ~[?:?]
        at com.sucy.skill.task.InventoryTask$AttribBuffs.apply(InventoryTask.java:346) ~[?:?]
        at com.sucy.skill.task.InventoryTask.run(InventoryTask.java:141) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[20:51:45 WARN]: [SkillAPI] Task #1261 for SkillAPI v3.84 generated an exception
java.lang.IllegalArgumentException: Max health must be greater than 0
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftLivingEntity.setMaxHealth(CraftLivingEntity.java:110) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.setMaxHealth(CraftPlayer.java:1215) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at com.sucy.skill.api.player.PlayerData.addMaxHealth(PlayerData.java:1337) ~[?:?]
        at com.sucy.skill.listener.AttributeListener.updatePlayer(AttributeListener.java:229) ~[?:?]
        at com.sucy.skill.api.player.PlayerData.addBonusAttributes(PlayerData.java:334) ~[?:?]
        at com.sucy.skill.task.InventoryTask$AttribBuffs.apply(InventoryTask.java:346) ~[?:?]
        at com.sucy.skill.task.InventoryTask.run(InventoryTask.java:141) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-1480adb-f92e01b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by Eniripsa96** [comment]
Found to be spigot.yml setting issue
