### ISSUE TITLE
Error on Mechanic: Particle Effect 

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#293]
When I cast a skill with this mechanic I get this error:

> [18:25:27] [Server thread/ERROR]: Failed to cast skill - newskill: Internal skill error
[18:25:27] [Server thread/WARN]: java.lang.NullPointerException
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.api.particle.ParticleEffect.<init>(ParticleEffect.java:113)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.api.particle.EffectPlayer.makeEffect(EffectPlayer.java:170)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.api.particle.EffectPlayer.start(EffectPlayer.java:105)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.mechanic.ParticleEffectMechanic.execute(ParticleEffectMechanic.java:49)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:354)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.Trigger$TriggerComponent.execute(Trigger.java:93)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.TriggerHandler.trigger(TriggerHandler.java:326)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.trigger(DynamicSkill.java:322)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:246)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:1996)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.api.player.PlayerSkillBar.apply(PlayerSkillBar.java:229)
[18:25:27] [Server thread/WARN]: 	at com.sucy.skill.listener.BarListener.onCast(BarListener.java:370)
[18:25:27] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:25:27] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:25:27] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:25:27] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[18:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[18:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1161)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:30)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:8)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:25:27] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:25:27] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[18:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[18:25:27] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Lix3nn53** [comment]
Thanks!
