### ISSUE TITLE
[BUG] NPE at getPlayerData

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#317]
I am not sure why this is happening but I got some errors in console.

> [07:05:48] [Server thread/INFO]: andersonmad lost connection: Disconnected
[07:05:48] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SkillAPI v1.76
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:405) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1102) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.sucy.skill.SkillAPI.getPlayerData(SkillAPI.java:463) ~[?:?]
	at com.sucy.skill.listener.BarListener.cleanup(BarListener.java:97) ~[?:?]
	at com.sucy.skill.listener.BarListener.onQuit(BarListener.java:126) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	... 12 more

And I get more NPEs at other events because of com.sucy.skill.SkillAPI.getPlayerData(SkillAPI.java:463)
This is kinda critical I think player's data get lost, but dont know what causes it. Maybe because of this?

**Comment by Lix3nn53** [comment]
I believe it was because of my mistakes on mysql operations
