### ISSUE TITLE
ClassCastException at EntityDamageByEntityEvent 

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#318]
> [07:41:34] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to SkillAPI v1.76
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1346) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityHorseAbstract.damageEntity(EntityHorseAbstract.java:166) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLargeFireball.a(EntityLargeFireball.java:22) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityFireball.B_(EntityFireball.java:74) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
	at com.rit.sucy.player.Protection.canAttack(Protection.java:76) ~[?:?]
	at com.rit.sucy.player.Protection.canAttack(Protection.java:56) ~[?:?]
	at com.sucy.skill.data.Settings.canAttack(Settings.java:379) ~[?:?]
	at com.sucy.skill.data.Settings.isAlly(Settings.java:393) ~[?:?]
	at com.sucy.skill.dynamic.target.AreaTarget.getTargets(AreaTarget.java:142) ~[?:?]
	at com.sucy.skill.dynamic.target.AreaTarget.execute(AreaTarget.java:112) ~[?:?]
	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:354) ~[?:?]
	at com.sucy.skill.dynamic.mechanic.ProjectileMechanic.callback(ProjectileMechanic.java:186) ~[?:?]
	at com.sucy.skill.listener.MechanicListener.onShoot(MechanicListener.java:247) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	... 21 more

**Comment by Eniripsa96** [comment]
Fixed in MCCore v1.67
