### ISSUE TITLE
Console error - Cannot measure distance between..

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#323]
> [06:08:27] [Server thread/ERROR]: Failed to cast skill - Enkaz Sarsisi: Internal skill error
[06:08:27] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and dungeons
[06:08:27] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:460)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.api.util.Nearby.getLivingNearby(Nearby.java:92)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.target.AreaTarget.getTargets(AreaTarget.java:132)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.target.AreaTarget.execute(AreaTarget.java:112)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:354)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.Trigger$TriggerComponent.execute(Trigger.java:93)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.TriggerHandler.trigger(TriggerHandler.java:327)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.trigger(DynamicSkill.java:322)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:246)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2011)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.api.player.PlayerSkillBar.apply(PlayerSkillBar.java:229)
[06:08:27] [Server thread/WARN]: 	at com.sucy.skill.listener.BarListener.onCast(BarListener.java:367)
[06:08:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
[06:08:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:08:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[06:08:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[06:08:27] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:08:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[06:08:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1161)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:30)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInHeldItemSlot.a(SourceFile:8)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[06:08:27] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:08:27] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[06:08:27] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[06:08:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Eniripsa96** [comment]
Not sure how it's getting targets in a separate world. Do you know when this happens? Is someone casting a certain skill then immediately changing worlds or something?

**Comment by Eniripsa96** [comment]
Should be fixed in 1.78
