### ISSUE TITLE
NPE at PlayerData#resetAll()

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#333]
> [05:27:59] [Server thread/WARN]: [LixRpgUtils] Task #102351 for LixRpgUtils v1.0 generated an exception
java.lang.NullPointerException: null
    at com.sucy.skill.dynamic.mechanic.PassiveMechanic.stopTasks(PassiveMechanic.java:86) ~[?:?]
    at com.sucy.skill.dynamic.DynamicSkill.stopEffects(DynamicSkill.java:226) ~[?:?]
    at com.sucy.skill.api.player.PlayerData.reset(PlayerData.java:1330) ~[?:?]
    at com.sucy.skill.api.player.PlayerData.resetAll(PlayerData.java:1359) ~[?:?]
    at com.utilities.PlayerAccountUtils$2.run(PlayerAccountUtils.java:204) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Eniripsa96** [comment]
Looks like it's trying to perform actions on a player that has logged off. Is there a reason you are trying to do that?

**Comment by Lix3nn53** [comment]
Yea sometimes I need to reset one of the player's accounts using api. Since my data and skillapi data works togerher I made a command that removes both skillapi and my data at once. Then I kick the player. Idk how to explain I want to kick the player after this so..

**Comment by Eniripsa96** [comment]
If you're kicking the player afterwards, they should still be online and this wouldn't fail. Make sure you're doing so after calling the SkillAPI methods rather than off of a player kicked/quit event.

**Comment by Lix3nn53** [comment]
> if(SkillAPI.hasPlayerData(p)) {
			PlayerAccounts acc = SkillAPI.getPlayerAccountData(p);
			if(acc.hasData(acctoremove)) {
				PlayerData data = acc.getData(acctoremove);
				try {
    	    		data.resetAll();
    	    	} catch (NullPointerException e) {
    	    		LixRpgUtils.getInstance().getLogger().info("Caught NPE while removing SkillAPI Account");
    	    	}
			}
		}
