### ISSUE TITLE
Update Ideas #1|2  / Error

### ISSUE THREAD

**Issue by KookaiPLZ** [Eniripsa96/SkillAPI#341]
Hey,
I collected some update ideas,
that would be good for my project and / or in general
would bring an 'improvement' if you understand
what I mean.

trigger:
standstill (becomes active if you have not moved since [second count])
killstreak (Dopplekill / Tripplekill / ... [kill count] in [seconds count]
death (In case of death / Maybe even that the damage is intercepted and you can resuscitate or something)
----------------------------------------- | -
targets:
looking (target = the one to look at)
block (the block looked at)
chain (multiple targets closest to the [range]
----------------------------------------- | -
Conditions:
weather (self explaining)
cooldown (When the cooldown is at a certain number /% - or just if there is cooldown or the skill is available)
level (level of the player)
killstreak (Only if your Killstreak is [number]
channeling (Maybe only, if you are currently channeling, i dont know about that idea, but maybe its something)
lava (same as water with lava EVEN if its possible with block)
----------------------------------------- | -
Mechanics:
I forgot about the mechanics, ill write an part 2 soon.

I still have a question, could you tell me what I should do to fix these Errormsgs?
:
-------------------------------------------------------------------------------------------------------------------
[10:38:20 WARN]: [SkillAPI] Task #15 for SkillAPI v3.103 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:823) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at com.sucy.skill.task.GUITask.run(GUITask.java:128) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[10:38:20 WARN]: [SkillAPI] Task #15 for SkillAPI v3.103 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:823) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at com.sucy.skill.task.GUITask.run(GUITask.java:128) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[10:38:20 WARN]: [SkillAPI] Task #15 for SkillAPI v3.103 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:823) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at com.sucy.skill.task.GUITask.run(GUITask.java:128) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[10:38:21 WARN]: [SkillAPI] Task #15 for SkillAPI v3.103 generated an exception
java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:823) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at com.sucy.skill.task.GUITask.run(GUITask.java:128) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3d850ec-809c399]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-3d850ec-809c399]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
-------------------------------------------------------------------------------------------------------------------
It always gets spammed, when someone isnt in a class.

**Comment by Zicerite** [comment]
I can think of a reason for why a Condition: Lava should exist.
The block condition only covers what is under you, so if you are in a 1 block deep thing of lava, and go in it and sit at the bottom of it, the block condition won't pass, because you aren't on top of the lava, but rather inside of it.

**Comment by Zicerite** [comment]
To Purge, in this context, is to get rid of a positive status effect. In skillapi  they would be the Absorb and Invincible status effects

**Comment by KookaiPLZ** [comment]
Ah, then I have to take back something
