### ISSUE TITLE
[Console Error] Spigot 1.13 + WG7

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#356]
> [16:32:35 ERROR]: Could not pass event PlayerCastSkillEvent to SkillAPI v1.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2012) ~[?:?]
        at com.sucy.skill.api.player.PlayerSkillBar.apply(PlayerSkillBar.java:229) ~[?:?]
        at com.sucy.skill.listener.BarListener.onCast(BarListener.java:367) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1401) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at com.sucy.skill.hook.WorldGuardHook.getRegionIds(WorldGuardHook.java:22) ~[?:?]
        at com.sucy.skill.listener.AddonListener.onSkillUse(AddonListener.java:93) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        ... 26 more

This is my code to loop regions for 1.13 spigot and WG7

ApplicableRegionSet regions =                 WorldGuard.getInstance().getPlatform().getRegionContainer().get(BukkitAdapter.adapt(p.getWorld())).getApplicableRegions(BukkitAdapter.adapt(p.getLocation()).toVector());
for(ProtectedRegion rg : regions) {	

}

**Comment by Zicerite** [comment]
Are using the latest world guard build? This seems similar to #349

**Comment by Lix3nn53** [comment]
Seems like I was a few versions behind with skillapi but I still get error. This is different tho 

> [03:16:43 ERROR]: Could not pass event PlayerCastSkillEvent to SkillAPI v1.81
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2012) ~[?:?]
        at com.sucy.skill.api.player.PlayerSkillBar.apply(PlayerSkillBar.java:229) ~[?:?]
        at com.sucy.skill.listener.BarListener.onCast(BarListener.java:367) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1401) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-6997012]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
        at com.sucy.skill.hook.WorldGuardHook.getRegionIds(WorldGuardHook.java:24) ~[?:?]
        at com.sucy.skill.listener.AddonListener.onSkillUse(AddonListener.java:93) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-6997012]
        ... 26 more

**Comment by Eniripsa96** [comment]
Which World Guard build are you using?

**Comment by Lix3nn53** [comment]
http://builds.enginehub.org/job/worldguard/10277

BUILD 1733

**Comment by Eniripsa96** [comment]
Looks like WG drastically changed their APIs. I'll see what I can do.

**Comment by Lix3nn53** [comment]
Yea I will send it again incase you didnt see
New code to loop regions in a loc

ApplicableRegionSet regions = WorldGuard.getInstance().getPlatform().getRegionContainer().get(BukkitAdapter.adapt(p.getWorld())).getApplicableRegions(BukkitAdapter.adapt(p.getLocation()).toVector());
for(ProtectedRegion rg : regions) {

}
