### ISSUE TITLE
[Console Warn] minecraft 1.13 RedStone particles

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#359]
> [03:18:53 WARN]: java.lang.reflect.InvocationTargetException
[03:18:53 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
[03:18:53 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:18:53 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[03:18:53 WARN]:        at com.sucy.skill.api.particle.Particle.make(Particle.java:225)
[03:18:53 WARN]:        at com.sucy.skill.api.particle.SpigotParticles.play(SpigotParticles.java:37)
[03:18:53 WARN]:        at com.sucy.skill.api.particle.SpigotParticles.play(SpigotParticles.java:20)
[03:18:53 WARN]:        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:212)
[03:18:53 WARN]:        at com.sucy.skill.api.util.ParticleHelper.fillSphere(ParticleHelper.java:307)
[03:18:53 WARN]:        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:168)
[03:18:53 WARN]:        at com.sucy.skill.api.projectile.ParticleProjectile.run(ParticleProjectile.java:215)
[03:18:53 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76)
[03:18:53 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[03:18:53 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877)
[03:18:53 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[03:18:53 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[03:18:53 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[03:18:53 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[03:18:53 WARN]: Caused by: java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
[03:18:53 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[03:18:53 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftParticle.toNMS(CraftParticle.java:123)
[03:18:53 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftParticle.toNMS(CraftParticle.java:108)
[03:18:53 WARN]:        ... 17 more

**Comment by Eniripsa96** [comment]
Fixed in 1.82
