### ISSUE TITLE
Internal error occurs when I use /class customize

### ISSUE THREAD

**Issue by EvosCorner** [Eniripsa96/SkillAPI#360]
hey, so i have a problem with skillAPI, and i dunno how to fix it. i tried to type in /class customize, and it allowed me to edit everything and all, but then when i loaded a new skill into skillAPI, and i try to type in /class customize, i get an internal error. What is weird to me is that even if i remove the skill, and reload the plugin, it still gives me an internal error. ive tried everything to change it back, and the only way i know how is by using a backup.

this is the console when i type in /class customize, then /class reload, and finally another /class customize:

[20:26:26] [Server thread/INFO]: EvosCorner issued server command: /class customize

[20:26:43] [Server thread/INFO]: EvosCorner issued server command: /class reload
[20:26:43] [Server thread/INFO]: Registration complete
[20:26:43] [Server thread/INFO]: - 4 skills
[20:26:43] [Server thread/INFO]: - 1 classes
[20:26:50] [Server thread/INFO]: EvosCorner issued server command: /class customize
[20:26:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'class customize' in class
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
at com.sucy.skill.api.classes.RPGClass.getToolIcon(RPGClass.java:328) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.populateClassSelection(GUITool.java:411) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.populate(GUITool.java:344) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.setType(GUITool.java:306) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.open(GUITool.java:296) ~[?:?]
at com.sucy.skill.cmd.CmdCustomize.execute(CmdCustomize.java:56) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
... 14 more

I hope either the author, or someone else can help me with this problem. I'm running 1.12.2 spigot.

**Comment by Zicerite** [comment]
I haven't ever seen an error like that before. 
Im assuming you are using the latest spigot build, with Skillapi Premium 1.81 right?

**Comment by EvosCorner** [comment]
yea, I'm using SkillAPI Premium 1.81 atm

**Comment by Zicerite** [comment]
After looking at the error again, it looks like an icon is invalid.
Try changing it back to default, or just delete the gui.yml and start it over.

**Comment by EvosCorner** [comment]
alright, ill try that, never though of that

**Comment by EvosCorner** [comment]
well I deleted the gui.yml, and i still got the internal error. Decided to bomb the whole skillAPI folder. for future viewers tho, this is what i found in the console:

[02:37:03] [Server thread/INFO]: EvosCorner issued server command: /class customize
[02:37:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'class customize' in class
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
at com.sucy.skill.api.classes.RPGClass.getToolIcon(RPGClass.java:328) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.populateClassSelection(GUITool.java:411) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.populate(GUITool.java:344) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.setType(GUITool.java:306) ~[?:?]
at com.sucy.skill.gui.tool.GUITool.open(GUITool.java:296) ~[?:?]
at com.sucy.skill.cmd.CmdCustomize.execute(CmdCustomize.java:56) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558) ~[?:?]
at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-642f6d2-57ab4cf]
... 14 more

**Comment by Zicerite** [comment]
Same error.
Did you also try just bombing the whole skillapi folder, but only when the server wasn't running?

**Comment by Eniripsa96** [comment]
Looks like it would be a material without item metadata. Are you using a block material?
