### ISSUE TITLE
[Console Warn] 1.13 another warn about particles

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#363]
> [12:03:04 WARN]: java.lang.IllegalArgumentException: Red is not between 0-255: 280
[12:03:04 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:93)
[12:03:04 WARN]:        at org.bukkit.Color.<init>(Color.java:164)
[12:03:04 WARN]:        at org.bukkit.Color.fromRGB(Color.java:119)
[12:03:04 WARN]:        at com.sucy.skill.api.particle.Particle.make(Particle.java:252)
[12:03:04 WARN]:        at com.sucy.skill.api.particle.SpigotParticles.play(SpigotParticles.java:36)
[12:03:04 WARN]:        at com.sucy.skill.api.particle.SpigotParticles.play(SpigotParticles.java:19)
[12:03:04 WARN]:        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:212)
[12:03:04 WARN]:        at com.sucy.skill.api.util.ParticleHelper.fillSphere(ParticleHelper.java:307)
[12:03:04 WARN]:        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:168)
[12:03:04 WARN]:        at com.sucy.skill.dynamic.mechanic.ParticleAnimationMechanic$ParticleTask.run(ParticleAnimationMechanic.java:172)
[12:03:04 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:03:04 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:03:04 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877)
[12:03:04 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[12:03:04 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[12:03:04 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[12:03:04 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Eniripsa96** [comment]
What are your settings for the particle?

**Comment by Eniripsa96** [comment]
Fixed in 1.85
