### ISSUE TITLE
Console Warn, spigot 1.13

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#382]
> [12:52:16 WARN]: [SkillAPI] Task #4752 for SkillAPI v1.87 generated an exception
java.lang.NumberFormatException: For input string: "0.4"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
        at com.sucy.skill.api.Settings.getInt(Settings.java:173) ~[?:?]
        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:192) ~[?:?]
        at com.sucy.skill.api.util.ParticleHelper.fillSphere(ParticleHelper.java:309) ~[?:?]
        at com.sucy.skill.api.util.ParticleHelper.play(ParticleHelper.java:170) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.ParticleAnimationMechanic$ParticleTask.run(ParticleAnimationMechanic.java:172) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-2b0e71c-15da706]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Eniripsa96** [comment]
Looks like you have 0.4 for the amount of a particle which isn't allowed

**Comment by Lix3nn53** [comment]
oh okay, thanks
