### ISSUE TITLE
SkillAPI v3.108 Loading error on 1.7.10 cauldron server

### ISSUE THREAD

**Issue by Xiazihong** [Eniripsa96/SkillAPI#422]
[22:04:45] [Server thread/INFO]: [SkillAPI] Enabling SkillAPI v3.108
[22:04:45] [Server thread/INFO]: [SkillAPI] Created a new folder for config files
[22:04:45] [Server thread/INFO]: [SkillAPI] Created a new folder for config files
[22:04:46] [Server thread/INFO]: Registration complete
[22:04:46] [Server thread/INFO]:  - 0 skills
[22:04:46] [Server thread/INFO]:  - 0 classes
[22:04:46] [Server thread/WARN]: java.lang.NullPointerException
[22:04:46] [Server thread/WARN]: 	at com.sucy.skill.listener.KillListener.<init>(KillListener.java:68)
[22:04:46] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:162)
[22:04:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[22:04:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:359)
[22:04:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[22:04:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420)
[22:04:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352)
[22:04:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507)
[22:04:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481)
[22:04:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441)
[22:04:46] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353)
[22:04:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[22:04:46] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by NicholasFRG** [comment]
According to the CurseForge page, 3.106 is the latest version that support 1.7.10 server, 3.108 only support 1.8 and above.

**Comment by Eniripsa96** [comment]
This is not a fatal error. I've been meaning to actually remove that log message. This is just due to some non-critical reflection calls not functioning for cauldron specifically, but the plugin should still be operational.
