### ISSUE TITLE
[Bug?]console error on KCaudron 1.7.10 server

### ISSUE THREAD

**Issue by NicholasFRG** [Eniripsa96/SkillAPI#424]
I'm using SAPI v3.106 and MCCore v1.67 but I still get error like this

> [23:52:10 ERROR]: Could not pass event EntityDamageByEntityEvent to SkillAPI v3.
106
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(Craf
tEventFactory.java:102) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDama
geEvent(CraftEventFactory.java:597) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHO
T]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDa
mageEvent(CraftEventFactory.java:465) [CraftEventFactory.class:1.7.10-R0.1-SNAPS
HOT]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEn
tityDamageEvent(CraftEventFactory.java:629) [CraftEventFactory.class:1.7.10-R0.1
-SNAPSHOT]
        at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBas
e.java:1381) [sv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.j
ava:903) [sv.class:?]
        at noppes.npcs.entity.EntityNPCInterface.func_70097_a(EntityNPCInterface
.java:520) [EntityNPCInterface.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.ja
va:1404) [yz.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPl
ayServer.java:1558) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(So
urceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(So
urceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldError: ARMOR_STAND
        at com.sucy.skill.listener.AddonListener.onAllyCheckArmorStand(AddonList
ener.java:121) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        

>

**Comment by NicholasFRG** [comment]
And the [message] function seems not working too

**Comment by Eniripsa96** [comment]
This was fixed in premium, but I seem to have missed it in the free version. Will fix.
