### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Precise323** [Eniripsa96/SkillAPI#482]
Can someone tell me what is causing this?

[23:39:42 INFO]: [SkillAPI] Enabling SkillAPI v3.108*
[23:39:42 ERROR]: Error occurred while enabling SkillAPI v3.108 (Is it up to date?)
java.lang.StackOverflowError: null
at java.util.ArrayList.addAll(ArrayList.java:581) ~[?:1.8.0_212]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:409) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
at com.sucy.skill.api.classes.RPGClass.getSkills(RPGClass.java:410) ~[?:?]
[Pterodactyl Daemon] Your server is sending too much data too quickly! Automatic spam detection triggered.

**Comment by Eniripsa96** [comment]
Looks like a class has its parent set to itself (or there's some sort of circular reference).

**Comment by PreciseKill** [comment]
This is the classes.yml https://pastebin.com/xZfQK30v
