### ISSUE TITLE
Error in consol when reloading

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#483]
Hi,

I'm on skillapi premium 1.89 and i've just upgrad my server on 1.14.4.
When i do a /class reload, i've the following error just after some secondes :

[19:35:32] [Thread-71/WARN]: java.lang.IllegalStateException: PlayerManaGainEvent cannot be triggered asynchronously from another thread.
[19:35:32] [Thread-71/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511)
[19:35:32] [Thread-71/WARN]:    at com.sucy.skill.api.player.PlayerData.giveMana(PlayerData.java:1485)
[19:35:32] [Thread-71/WARN]:    at com.sucy.skill.api.player.PlayerData.regenMana(PlayerData.java:1453)
[19:35:32] [Thread-71/WARN]:    at com.sucy.skill.task.ManaTask.run(ManaTask.java:67)
[19:35:32] [Thread-71/WARN]:    at com.sucy.skill.thread.RepeatThreadTask.tick(RepeatThreadTask.java:62)
[19:35:32] [Thread-71/WARN]:    at com.sucy.skill.thread.MainThread.run(MainThread.java:61)

Any clue from which it could come from ?

**Comment by xxJinxedxx** [comment]
It's an issue with the "Mana" feature.
Currently 1.14.* is not fully supported until the new Kotlin rewrite comes out.

**Comment by Tiplish** [comment]
I hope there will be a patch for it soon before the release of the Kotlin version :(

**Comment by xxJinxedxx** [comment]
Most likely not. Stove said that there will be small patches here and there but no major updates, which will certainly mean support for versions that are not currently supported. At least from what he said.
Let's hope that Kotlin will be out soon.

**Comment by Tiplish** [comment]
Resolved with the last update, thanks Eniripsa :D
