### ISSUE TITLE
SkillAPI not compatible with 1.19

### ISSUE THREAD

**Issue by michaeltebo** [Eniripsa96/SkillAPI#517]
```
[01:00:59] [Server thread/INFO]: [SkillAPI] Enabling SkillAPI v3.108*
[01:01:00] [Server thread/INFO]: Registration complete
[01:01:00] [Server thread/INFO]:  - 0 skills
[01:01:00] [Server thread/INFO]:  - 0 classes
[01:01:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because "living" is null
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.listener.KillListener.<init>(KillListener.java:68)
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:162)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:00] [Server thread/WARN]: [SkillAPI] Failed to set up packet listener - some click combos may not behave properly
[01:01:00] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.EntityPlayer
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.packet.PacketInjector.<init>(PacketInjector.java:33)
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:168)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because the return value of "com.rit.sucy.reflect.Reflection.getNMSClass(String)" is null
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.packet.PacketInjector.<init>(PacketInjector.java:54)
[01:01:00] [Server thread/WARN]: 	at SkillAPI.jar//com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:168)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[01:01:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[01:01:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:01:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
...
[09:11:53] [Server thread/INFO]: [SkillAPI] Disabling SkillAPI v3.108
```
Error appears on every server load.

**Comment by jayofearth** [comment]
Ran into the same issue. Oddly enough, I fell into this rabbit hole because v1.1.8.1 was working with some minor, but disabling, bugs.
