### ISSUE TITLE
SkillAPI Premium - /class customize Incompatibility with VentureChat

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#67]
Hey Eniri,
The third issue is as follows:
When using the SkillAPI plugin with VentureChat, a popular chat plugin, the following error is thrown when the /class customize GUI is used and nothing can be edited. Only when the VentureChat plugin is disabled or unloaded does the GUI function as intended.

```
> [23:17:25 ERROR]: Could not pass event InventoryClickEvent to VentureChat v2.9.9
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1854) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
>         at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> Caused by: java.lang.NullPointerException
>         at mineverse.Aust1n46.chat.listeners.CommandListener.InventoryClick(CommandListener.java:273) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
>         ... 15 more
```

**Comment by Eniripsa96** [comment]
I'm not sure if I'll be able to fix this issue. It likely can only be fixed on their end. You should bring it up with the owner of that plugin. I'll keep this open just in case I do find something though until it's resolved on either end.
