### ISSUE TITLE
SQL Data Isertion Issues

### ISSUE THREAD

**Issue by asalinas212** [Eniripsa96/SkillAPI#72]
It connected and built the table just fine, but it seems like when it's trying to insert or pull the data, it's getting some errors. Plugin works just fine when not using MySQL.

[13:34:08 INFO]: [SkillAPI] Connecting to MySQL database...
[13:34:08 INFO]: [SkillAPI] Connected to the MySQL database successfully
[13:34:08 ERROR]: Error occurred while enabling SkillAPI v3.94 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at com.rit.sucy.sql.direct.SQLTable.createEntry(SQLTable.java:263) ~[?:?]
        at com.sucy.skill.data.io.SQLIO.loadData(SQLIO.java:110) ~[?:?]
        at com.sucy.skill.SkillAPI.loadPlayerData(SkillAPI.java:495) ~[?:?]
        at com.sucy.skill.SkillAPI.getPlayerAccountData(SkillAPI.java:568) ~[?:?]
        at com.sucy.skill.SkillAPI.getPlayerData(SkillAPI.java:474) ~[?:?]
        at com.sucy.skill.listener.BarListener.<init>(BarListener.java:68) ~[?:?]
        at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:147) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:358) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:320) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:726) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.Bukkit.reload(Bukkit.java:548) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:612) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:398) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:362) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at java.lang.Thread.run(Thread.java:701) [?:1.6.0_38]
Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'Y'
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:769) ~[?:1.6.0_38]
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:576) ~[?:1.6.0_38]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:501) ~[?:1.6.0_38]
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:476) ~[?:1.6.0_38]
        at com.rit.sucy.sql.direct.SQLEntry.<clinit>(SQLEntry.java:43) ~[?:?]
        ... 23 more

Wondering if this is something fixable from my side, or if the plugin itself needs to be corrected.

**Comment by Eniripsa96** [comment]
Fixed in MCCore v1.58
