### ISSUE TITLE
Could not pass event PlayerInteractEvent to MCCore v1.58

### ISSUE THREAD

**Issue by asalinas212** [Eniripsa96/SkillAPI#73]
[17:29:52 ERROR]: Could not pass event PlayerInteractEvent to MCCore v1.58
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:111) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:821) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:688) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_111]
        at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_111]
        at com.sucy.skill.gui.SkillListMenu.getSkill(SkillListMenu.java:63) ~[?:?]
        at com.sucy.skill.gui.SkillDetailMenu.setup(SkillDetailMenu.java:172) ~[?:?]
        at com.rit.sucy.gui.MapData.setup(MapData.java:175) ~[?:?]
        at com.rit.sucy.gui.MapData.next(MapData.java:161) ~[?:?]
        at com.rit.sucy.gui.MapMenuManager.sendNext(MapMenuManager.java:154) ~[?:?]
        at com.sucy.skill.gui.SkillListMenu.onSelect(SkillListMenu.java:187) ~[?:?]
        at com.rit.sucy.gui.MapListener.onInteract(MapListener.java:149) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_111]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        ... 18 more
[17:29:52 WARN]: Failed to handle packet for /10.10.0.25:15475
net.minecraft.server.v1_10_R1.ReportedException: Ticking player
        at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:323) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.PlayerConnection.E_(PlayerConnection.java:137) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.E_(AbstractListenerPlayIn.java:80) ~[?:?]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:224) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(SourceFile:187) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:758) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547) [craftbukkit-latest.jar:git-Bukkit-43ab266]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.lang.NullPointerException
        at com.sucy.skill.gui.SkillDetailMenu.render(SkillDetailMenu.java:222) ~[?:?]
        at com.rit.sucy.gui.MapData.render(MapData.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.map.CraftMapView.render(CraftMapView.java:146) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.sendMap(CraftPlayer.java:425) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at com.rit.sucy.gui.MapData.render(MapData.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.map.CraftMapView.render(CraftMapView.java:146) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:287) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.WorldMap.a(WorldMap.java:243) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.ItemWorldMap.a(ItemWorldMap.java:191) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        at net.minecraft.server.v1_10_R1.EntityPlayer.k_(EntityPlayer.java:248) ~[craftbukkit-latest.jar:git-Bukkit-43ab266]
        ... 9 more

Throws this exception when attempting to view skill tree and also logs player out of the server.

**Comment by Eniripsa96** [comment]
Likely related to the images missing from the build. Since those are added back in, closing this issue.
