### ISSUE TITLE
Get kicked from server after selecting the default Psykin class

### ISSUE THREAD

**Issue by Devillion** [Eniripsa96/SkillAPI#88]
I'm using the premium version.

After using the /class profess command as soon as I became the default class I got kicked from server.

This is the error that comes up in bungeecord console, there is no error in the servers console

Now, every time I login I just get kicked with that error.

Using latest spigot build from a few days ago.

http://i.imgur.com/kRkU4Gf.png

**Comment by Eniripsa96** [comment]
It wasn't intentional to have that class even available yet, so if it's just that class, I can see why it would likely break. I may investigate coded classes though to make sure they don't cause issues overall.

**Comment by Devillion** [comment]
I made a new class with the editor and I get the same error when I try to join it.

**Comment by Devillion** [comment]
I just tried today's latest skillapi premium update and this issue is still  happening.

I can't join any class I make, it just keeps kicking me.

**Comment by Eniripsa96** [comment]
Odd, I'm not able to replicate it and there's no lines that trace back to SkillAPI in that log you showed, so I'm having a hard time figuring out why it would happen.

**Comment by cwkfr** [comment]
Same problem here, using the free version.

Everytime I tried to connect, there are errors on the console:
lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
or
lost connection: Internal Exception: java.io.IOException: Error while write(...): failed to write
or
just "Disconnected."

Plugin list:
Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, GroupManager, MCCore (Latest), Multiverse-Core, Parties, PlugMan, ProtocolLib, SkillAPI, Vault, VoxelSniper, WorldEdit, WorldGuard, WorldGuardFix

Also the plugin version is 3.94 (but actually the latest version 3.95)

**Comment by cwkfr** [comment]
Well, it seems bungeecord causing the problem. Tested on local server without bungee, work flawlessly.
And when I tried to connect with bungee:

`<-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IllegalArgumentException: Objective Hunter already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
    at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:54)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Unknown Source)
05:36:10 [INFO] disconnected with: IllegalArgumentException : Objective Hunter already exists in this scoreboard @ com.google.common.base.Preconditions:145
05:36:10 [INFO] <-> DownstreamBridge <-> [lobby] has disconnected`

**Comment by Eniripsa96** [comment]
That would make sense why I wouldn't catch it, since I don't test with BungeeCord. The question is what is BungeeCord doing that causes scoreboards to break. It's particularly strange how the stack trace doesn't find its way back to SkillAPI at all. I'm fearing that it may be an issue with BungeeCord that I may not be able to get around.

**Comment by DrkMatr1984** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/score/Scoreboard.java
You could probably somehow check for bungeecord, the way some of the dual-bungeecord-spigot servers check, and then do ScoreBoard.clear on login for users with this spigot API.

**Comment by DrkMatr1984** [comment]
It's probably because you set the scoreboard with the bukkit/spigot api, and then BungeeCord tries to add the same scoreboard right after. It may also be that simply putting a delay on loading the Bukkit Scoreboard may stop this problem. Like maybe have the scoreboard for bukkit start 2-5 seconds after the player logs in so the bungee scoreboard has time to set first before the bukkit one does, and then perhaps the bukkit scoreboard will simply override the bungee scoreboard.

**Comment by Eniripsa96** [comment]
Fixed in MCCore v1.59
